# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      working-directory: ./AirportAutomation
      run: dotnet restore AirportАutomation.sln

    - name: Build
      working-directory: ./AirportAutomation
      run: dotnet build AirportАutomation.sln --no-restore

    - name: Test
      working-directory: ./AirportAutomation
      run: dotnet test AirportАutomation.sln --no-build --verbosity normal




